apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
spec:
  hosts:
    - "default.localtest.me"
  gateways:
    - nginx-gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: nginx-service
            port:
              number: 80
